version: '3.3'

services:
  web:
    build: .
    command: sh -c "sleep 10 && gunicorn config.wsgi:application --bind 0.0.0.0:8000 && python3 manage.py collectstatic --noinput"
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/src/app/media/
    ports:
      - "8080:8080"
    depends_on:
      - db_qr
      - redis
      - migration
    container_name: web
    networks:
      - backend
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    expose:
      - "8080"
  db_qr:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: acer
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: accelerate
    container_name: db_qr
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    networks:
      - backend
  migration:
    build: .
    restart: on-failure
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000 && python3 manage.py collectstatic --noinput"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db_qr
    networks:
      - backend
  celery:
    build: .
    command: celery -A config worker -l DEBUG
    volumes:
      - .:/usr/src/app/
    depends_on:
      - web
      - redis
    networks:
      - backend
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    command: nginx -g 'daemon off;'
    ports:
      - "8080:80"
    volumes:
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/src/app/media/
    depends_on:
      - web
    networks:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  backend: